# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/javascript?view=azure-devops
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'


pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- task: Npm@1
  inputs:
    command: 'install'
    customRegistry: 'useFeed'
    customFeed: '184f97a3-2268-4478-b14e-7644d051572c'

- script: |
    npm test


- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-RESULTS.xml'
    testRunTitle: 'Test results for JavaScript'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    vstsFeed: '184f97a3-2268-4478-b14e-7644d051572c'
    vstsFeedPackage: '8bc71e1a-ec02-4a11-a89a-809e68a9bc26'
    vstsPackageVersion: '1.0.0'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '184f97a3-2268-4478-b14e-7644d051572c'
    vstsFeedPackagePublish: 'universaldemo'
    versionOption: 'patch'
    verbosity: 'Debug'

- task: PublishBuildArtifacts@1