# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
  - name: buildApp
    displayName: Build web app?
    default: false
    type: boolean
    
trigger:
- master

pr: none

jobs:
- job: 
  steps:
    - script: echo $(Build.BuildId)
    - script: echo ${{ variables.Build.BuildId }}

- ${{ if gt(variables.Build.BuildId, 0) }}:
  - template: car.yml
    parameters:
      auto: false
      wheels: 3
      brand: toyota

- ${{ if parameters.buildApp }}:
  - template: job.template.yml
    parameters:
      name: Linux
      pool:
        vmImage: 'ubuntu-latest'

  - template: job.template.yml
    parameters:
      name: macOS
      pool:
        vmImage: 'macos-latest'
        
  - template: job.template.yml
    parameters:
      name: LocalAgent
      pool: Default
