# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'vs2017-win2016' # examples of other options: 'macOS-10.15', 'vs2017-win2016'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- task: Npm@1
  inputs:
  command: 'install'
- task: Npm@1
  inputs:
    customEndpoint: <Name of npm service connection>
- task: npmAuthenticate@0
  inputs:
    customEndpoint: <Name of npm service connection>
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TEST-RESULTS.xml'
- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura # or JaCoCo
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
 - script: |
    npm install -g @angular/cli
    npm install
    ng build --prod  

- script: |
    npm install --only=dev
    npm run build
- script: npm install --only=dev
- script: npx mocha
- script: npm install -g @angular/cli
- script: npm install
- script: yarn install
- script: npm run compile
- script: tsc --target ES6 --strict true --project tsconfigs/production.json
- script: mocha test --reporter mocha-junit-reporter
- script: npm test
- script: |
    npm install
    npm run build
 displayName: 'npm install and build'
- script: webpack
- script: npm run build

  displayName: 'npm install and build'
