# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: build
  displayName: 'build stage'
  jobs:
  - template: job.template.yml
    parameters:
      name: Linux
      pool:
        vmImage: 'ubuntu-latest'

  - template: job.template.yml
    parameters:
      name: macOS
      pool:
        vmImage: 'macos-latest'
  - template: job.template.yml
    parameters:
      name: LocalAgent
      pool: Default
