# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Test Group Var #DOOOOPE

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js' # test

- script: |
    git config user.email "alexa.sparks@getflywheel.com"
    git config user.name "alexasparks"

    echo "publishRelease: $(publishRelease)"

    if [ "$(publishRelease)" = "true" ]; then
      echo "##vso[build.addbuildtag]test-tag"
    fi
  displayName: 'npm install and build'