# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Test Group Var #DOOOOPE

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js' # test

- script: |
    npm install
    npm run build

    git config user.email "alexa.sparks@getflywheel.com"
    git config user.name "alexasparks"

    echo "tag: $(GROUP_VAR_ONE)-test-$(Build.BuildId)"
    git tag -a "$(GROUP_VAR_ONE)-test-$(Build.BuildId)" -m "test-$(Build.BuildId)"
    git remote set-url origin https://github.com/alexasparks/pipelines-javascript.git
    git push origin HEAD:$(Build.SourceBranch) --tags
  displayName: 'npm install and build'