parameters:
- name: name
  type: string
  default: base
- name: jobs
  type: jobList
  
jobs:
  - job: 
    steps:  
      - script: echo "Welcome to $(name)"
        displayName: Welcome message
  - ${{ each job in parameters.jobs }}:
    - ${{ job }}
