parameters:
- name: name
  type: string
  default: base

jobs:
  - job: 
    steps:  
      - script: echo "Welcome to $(name)"
        displayName: Welcome message
  - ${{ each job in parameters.jobs }}:
    - ${{ each pair in job }}:
      - ${{ pair.key }}: ${{ pair.value }}
